--[[ GRM Weather & Time v1.0.0: authoritative clock, day/night, fog and sky. ]]
if SERVER then AddCSLuaFile()end
GRM=GRM or{};GRM.Weather=GRM.Weather or{};local W=GRM.Weather
W.Version="1.0.0";W.Types={clear={name="Ясно",fog=.08},cloudy={name="Облачно",fog=.22},fog={name="Туман",fog=.72},rain={name="Дождь",fog=.38},storm={name="Гроза",fog=.55}}
W.Config=W.Config or{dayLengthMinutes=90,randomWeather=true,weatherMinMinutes=12,weatherMaxMinutes=28,startHour=8,hudClock=true}
local OPEN="GRM_Weather_Admin";local SAVE="GRM_Weather_Save"
if GRM.Access and GRM.Access.Register then GRM.Access.Register("weather.manage",{label="Погода и время: управление",scope="account"})end
function W.CanAdmin(p)return IsValid(p)and(p:IsSuperAdmin()or(GRM.Access and GRM.Access.Can and GRM.Access.Can(p,"weather.manage")==true))end
function W.TimeMinutes()return GetGlobalFloat("GRM_TimeMinutes",W.Config.startHour*60)%1440 end
function W.FormatTime(minutes)minutes=math.floor(tonumber(minutes)or W.TimeMinutes())%1440;return string.format("%02d:%02d",math.floor(minutes/60),minutes%60)end
function W.Period(minutes)local h=(tonumber(minutes)or W.TimeMinutes())/60;if h<5 then return"Ночь"elseif h<8 then return"Утро"elseif h<18 then return"День"elseif h<22 then return"Вечер"else return"Ночь"end end
function W.SunFactor(minutes)local h=(tonumber(minutes)or W.TimeMinutes())/60;local x=math.sin(((h-6)/12)*math.pi);return math.Clamp(x,0,1)end
if SERVER then
 util.AddNetworkString(OPEN);util.AddNetworkString(SAVE);local FILE="grm_weather/config.json"
 local function load()local d=GRM.Persistence.LoadJSON(FILE,{version=1,config=W.Config,state={time=W.Config.startHour*60,weather="clear"}});if istable(d.config)then for k,v in pairs(d.config)do W.Config[k]=v end end;W._time=tonumber(d.state and d.state.time)or W.Config.startHour*60;W._weather=W.Types[d.state and d.state.weather]and d.state.weather or"clear"end
 local function save()return GRM.Persistence.SaveJSON(FILE,{version=1,config=W.Config,state={time=W._time,weather=W._weather}},{version=1})end
 load();SetGlobalFloat("GRM_TimeMinutes",W._time);SetGlobalString("GRM_Weather",W._weather);if GRM.Perm and GRM.Perm.RegisterClass then GRM.Perm.RegisterClass("grm_clock",true)end;if GRM.PermData and GRM.PermData.AddExtract then GRM.PermData.AddExtract("grm_clock",function(e)return{clockName=e:GetClockName()}end);GRM.PermData.AddApply("grm_clock",function(e,d)if d.clockName then e:SetClockName(string.Trim(tostring(d.clockName)):sub(1,64))end end)end
 local function skyPaint()local e=ents.FindByClass("env_skypaint")[1];if not IsValid(e)then e=ents.Create("env_skypaint");if IsValid(e)then e:SetPos(Vector(0,0,0));e:Spawn()end end;return e end
 local function applySky()
  local e=skyPaint();if not IsValid(e)or not isfunction(e.SetTopColor)then return end;local t=W._time;local sun=W.SunFactor(t);local h=t/60;local dusk=math.Clamp(1-math.abs(h-19)/2,0,1);local night=1-sun
  e:SetTopColor(Vector(.015+.18*sun+.16*dusk,.025+.32*sun+.06*dusk,.07+.58*sun+.02*dusk));e:SetBottomColor(Vector(.025+.42*sun+.35*dusk,.035+.52*sun+.12*dusk,.08+.72*sun+.04*dusk));e:SetSunColor(Vector(1,.72+.25*sun,.5+.45*sun));e:SetDuskColor(Vector(1,.18,.05));e:SetDuskScale(.25+1.2*dusk);e:SetDuskIntensity(.2+1.2*dusk);e:SetSunSize(2.5+2*sun);e:SetStarScale(.45+1.2*night);e:SetStarFade(1.2);e:SetStarSpeed(.01)
 end
 local function sync()SetGlobalFloat("GRM_TimeMinutes",W._time);SetGlobalString("GRM_Weather",W._weather);SetGlobalFloat("GRM_SunFactor",W.SunFactor(W._time));SetGlobalBool("GRM_WeatherHUD",W.Config.hudClock~=false)end
 local function nextWeather()if not W.Config.randomWeather then return end;local ids={"clear","clear","cloudy","fog","rain","storm"};W._weather=ids[math.random(#ids)];W._weatherUntil=CurTime()+math.random(W.Config.weatherMinMinutes*60,W.Config.weatherMaxMinutes*60);sync();save();if GRM.Audit then GRM.Audit.Write("weather","weather.change",nil,{}, {weather=W._weather})end end
 W._weatherUntil=CurTime()+math.random(W.Config.weatherMinMinutes*60,W.Config.weatherMaxMinutes*60)
 timer.Create("GRM_Weather_Clock",1,0,function()W._time=(W._time+1440/math.max(600,(tonumber(W.Config.dayLengthMinutes)or 90)*60))%1440;if CurTime()>=W._weatherUntil then nextWeather()end;sync();if math.floor(W._time)%5==0 then applySky()end end);timer.Simple(1,applySky);timer.Create("GRM_Weather_Autosave",120,0,save)
 hook.Add("InitPostEntity","GRM_Weather_Sky",function()timer.Simple(2,applySky)end);hook.Add("ShutDown","GRM_Weather_Save",save)
 local function adminData(p)if not W.CanAdmin(p)then return end;net.Start(OPEN);net.WriteTable(W.Config);net.WriteFloat(W._time);net.WriteString(W._weather);net.Send(p)end
 net.Receive(SAVE,function(bits,p)if not W.CanAdmin(p)then return end;if GRM.Net and not GRM.Net.Guard(p,"weather.admin.save",{rate=.5,burst=2,maxBits=65536},{bits=bits})then return end;local d=net.ReadTable()or{};W.Config.dayLengthMinutes=math.Clamp(tonumber(d.dayLengthMinutes)or 90,10,1440);W.Config.randomWeather=d.randomWeather~=false;W.Config.weatherMinMinutes=math.Clamp(math.floor(tonumber(d.weatherMinMinutes)or 12),2,240);W.Config.weatherMaxMinutes=math.Clamp(math.floor(tonumber(d.weatherMaxMinutes)or 28),W.Config.weatherMinMinutes,480);W.Config.hudClock=d.hudClock~=false;local hour=tonumber(d.hour);if hour then W._time=(hour%24)*60 end;if W.Types[d.weather]then W._weather=d.weather;W._weatherUntil=CurTime()+W.Config.weatherMaxMinutes*60 end;save();sync();applySky();if GRM.Audit then GRM.Audit.Write("weather","admin.save",p,{},d)end;adminData(p)end)
 concommand.Add("grm_weather_admin",adminData);concommand.Add("grm_time",function(p)if IsValid(p)then p:ChatPrint("[Время] "..W.FormatTime(W._time).." • "..W.Period(W._time).." • "..W.Types[W._weather].name)end end)
 hook.Add("PlayerSay","GRM_Weather_Chat",function(p,t)local s=string.lower(string.Trim(t or""));if s=="/time"or s=="/время"or s=="/weather"or s=="/погода"then p:ChatPrint("[Время] "..W.FormatTime(W._time).." • "..W.Period(W._time).." • "..W.Types[W._weather].name);return""elseif s=="/weather_admin"and W.CanAdmin(p)then adminData(p);return""end end)
 hook.Add("PlayerSayTransform","GRM_Weather_EasyChat",function(p,t,d)d=istable(t)and t or d;local raw=istable(t)and t[1]or t;local s=string.lower(string.Trim(raw or""));if s~="/time"and s~="/время"and s~="/weather"and s~="/погода"and s~="/weather_admin"then return end;if s=="/weather_admin"then if W.CanAdmin(p)then adminData(p)end else p:ChatPrint("[Время] "..W.FormatTime(W._time).." • "..W.Period(W._time).." • "..W.Types[W._weather].name)end;d.SkipPlayerSay=true;d[1]=""end)
 print("[GRM Weather] v"..W.Version.." server loaded")
end
if CLIENT then
 surface.CreateFont("GRMClock",{font="Roboto",size=22,weight=800,extended=true});surface.CreateFont("GRMWeather",{font="Roboto",size=14,weight=500,extended=true});local smoothFog=0
 hook.Add("SetupWorldFog","GRM_Weather_Fog",function()local typ=W.Types[GetGlobalString("GRM_Weather","clear")]or W.Types.clear;smoothFog=Lerp(FrameTime()*.4,smoothFog,typ.fog);if smoothFog<.02 then return end;local sun=GetGlobalFloat("GRM_SunFactor",1);render.FogMode(MATERIAL_FOG_LINEAR);render.FogStart(250*(1-smoothFog));render.FogEnd(Lerp(smoothFog,12000,900));render.FogMaxDensity(math.Clamp(smoothFog,0,.92));render.FogColor(50+80*sun,58+90*sun,70+105*sun);return true end)
 hook.Add("SetupSkyboxFog","GRM_Weather_SkyFog",function(scale)local typ=W.Types[GetGlobalString("GRM_Weather","clear")]or W.Types.clear;local d=typ.fog;render.FogMode(MATERIAL_FOG_LINEAR);render.FogStart(0);render.FogEnd(8000*scale);render.FogMaxDensity(math.Clamp(d*.8,0,.85));local s=GetGlobalFloat("GRM_SunFactor",1);render.FogColor(45+85*s,55+95*s,75+100*s);return true end)
 hook.Add("RenderScreenspaceEffects","GRM_Weather_Light",function()local sun=GetGlobalFloat("GRM_SunFactor",1);local weather=GetGlobalString("GRM_Weather","clear");local dark=1-sun;DrawColorModify({["$pp_colour_addr"]=0,["$pp_colour_addg"]=0,["$pp_colour_addb"]=dark*.012,["$pp_colour_brightness"]=-dark*.09,["$pp_colour_contrast"]=1+dark*.08,["$pp_colour_colour"]=1-dark*.35-(weather=="storm"and .15 or 0),["$pp_colour_mulr"]=0,["$pp_colour_mulg"]=0,["$pp_colour_mulb"]=0})end)
 local nextThunder,lightning=0,0
 hook.Add("Think","GRM_Weather_Thunder",function()if GetGlobalString("GRM_Weather","")~="storm"then return end;if RealTime()>=nextThunder then nextThunder=RealTime()+math.Rand(12,32);lightning=RealTime()+.16;surface.PlaySound("ambient/atmosphere/thunder1.wav")end end)
 hook.Add("HUDPaint","GRM_Weather_Precip",function()local typ=GetGlobalString("GRM_Weather","clear");if typ~="rain"and typ~="storm"then return end;surface.SetDrawColor(175,195,220,typ=="storm"and 105 or 75);local seed=math.floor(RealTime()*22);for i=1,55 do local x=(i*173+seed*47)%ScrW();local y=(i*97+seed*83)%ScrH();surface.DrawLine(x,y,x-8,y+22)end;if lightning>RealTime()then surface.SetDrawColor(220,230,255,75);surface.DrawRect(0,0,ScrW(),ScrH())end end)
 hook.Add("HUDPaint","GRM_Weather_Clock",function()if not GetGlobalBool("GRM_WeatherHUD",true)then return end;local weather=GetGlobalString("GRM_Weather","clear");local name=(W.Types[weather]or W.Types.clear).name;local t=W.FormatTime();local x=ScrW()-34;draw.SimpleText(t,"GRMClock",x,30,Color(240,243,248),TEXT_ALIGN_RIGHT);draw.SimpleText(W.Period().." • "..name,"GRMWeather",x,52,Color(170,180,195),TEXT_ALIGN_RIGHT)end)
 net.Receive(OPEN,function()local cfg=net.ReadTable()or{};local tm=net.ReadFloat();local weather=net.ReadString();if IsValid(W._frame)then W._frame:Remove()end;local f=vgui.Create("DFrame");W._frame=f;f:SetSize(680,620);f:Center();f:MakePopup();f:SetTitle("Погода и время GRM");if GRM.UI then GRM.UI.Track("weather.admin",f)end;local y=44;local function slider(name,min,max,val)local s=vgui.Create("DNumSlider",f);s:SetPos(18,y);s:SetSize(644,42);s:SetText(name);s:SetMin(min);s:SetMax(max);s:SetDecimals(0);s:SetValue(val);y=y+46;return s end;local day=slider("Длительность суток, реальные минуты",10,1440,cfg.dayLengthMinutes);local hour=slider("Текущее время, час",0,23,tm/60);local w=vgui.Create("DComboBox",f);w:SetPos(18,y);w:SetSize(644,36);for id,row in pairs(W.Types)do w:AddChoice(row.name,id,id==weather)end;y=y+46;local random=vgui.Create("DCheckBoxLabel",f);random:SetPos(18,y);random:SetText("Случайная смена погоды");random:SetValue(cfg.randomWeather and 1 or 0);random:SizeToContents();y=y+34;local mn=slider("Минимальная длительность погоды, мин",2,240,cfg.weatherMinMinutes);local mx=slider("Максимальная длительность погоды, мин",2,480,cfg.weatherMaxMinutes);local hud=vgui.Create("DCheckBoxLabel",f);hud:SetPos(18,y);hud:SetText("Показывать часы и погоду на HUD");hud:SetValue(cfg.hudClock~=false and 1 or 0);hud:SizeToContents();local b=vgui.Create("DButton",f);b:SetPos(18,550);b:SetSize(644,44);b:SetText("СОХРАНИТЬ И ПРИМЕНИТЬ");b.DoClick=function()local _,wid=w:GetSelected();net.Start(SAVE);net.WriteTable({dayLengthMinutes=day:GetValue(),hour=hour:GetValue(),weather=wid or weather,randomWeather=random:GetChecked(),weatherMinMinutes=mn:GetValue(),weatherMaxMinutes=mx:GetValue(),hudClock=hud:GetChecked()});net.SendToServer()end end)
end
