-- Jobs v4 contracts: placement tool, physical garbage, live taxi and vehicle classes.
local function read(p)local f=assert(io.open(p,"rb"));local s=f:read("*a");f:close();return s end
local core=read("lua/autorun/sh_grm_jobs.lua");local cfg=read("lua/autorun/sh_grm_jobs_config.lua");local v4=read("lua/autorun/sh_grm_jobs_v4.lua");local tool=read("lua/weapons/gmod_tool/stools/grm_jobs.lua");local bin=read("lua/entities/grm_garbage_bin/init.lua");local box=read("lua/entities/grm_garbage_box/init.lua");local dealer=read("lua/autorun/sh_grm_vehicle_dealer.lua");local dealerUI=read("lua/entities/sent_vehicle_dealer/cl_init.lua");local mobile=read("lua/autorun/sh_grm_mobile.lua");local q=read("lua/autorun/sh_grm_qmenu.lua")
local fail,n=0,0;local function ok(c,s)n=n+1;if c then print("  ok  "..s)else fail=fail+1;print("  FAIL "..s)end end
ok(cfg:find("function JB.AddWorkPoint",1,true)and cfg:find("RemoveNearestWorkPoint",1,true),"public typed point placement API")
ok(tool:find('TOOL.Category="GRM"',1,true)and tool:find("grm_jobs_point_type",1,true),"GRM jobs stool")
ok(tool:find('typ=="garbage"',1,true)and tool:find('ents.Create("grm_garbage_bin")',1,true),"garbage point creates physical bin")
ok(q:find('{ id = "grm_jobs"',1,true)and q:find("grm_jobs_spawn_bin",1,true),"jobs tool is exposed in custom Q with schema")
ok(cfg:find("Транспорт работ",1,true)and cfg:find("Разрешить для ТАКСИ",1,true)and cfg:find("Разрешить для МУСОРОВОЗА",1,true)and cfg:find("Разрешить для ДОСТАВКИ",1,true),"structured vehicle assignment menu")
ok(cfg:find("courierVehicles",1,true)and cfg:find("garbageCapacity",1,true)and cfg:find("garbageBinCooldown",1,true),"all job vehicle and garbage settings persist")
ok(cfg:find("IsVehicleClassAllowed",1,true)and cfg:find("VehicleTokens",1,true),"vehicle validation supports class and SpawnName")
ok(bin:find("SearchGarbageBin",1,true)and bin:find("TrashDumpster02.mdl",1,true),"searchable garbage bin entity")
ok(box:find("models/props/cs_office/cardboard_box03.mdl",1,true),"requested garbage box model")
ok(box:find("AttachTo",1,true)and box:find("GRM_GarbageBox",1,true),"box is visibly carried by player")
ok(v4:find("GRM_SearchingGarbage",1,true)and v4:find("garbageSearchTime",1,true),"garbage rummaging has server progress lock")
ok(v4:find("KEY_G",1,true)and v4:find("GRM_JobsV4_GarbageLoad",1,true),"G loads carried box")
ok(v4:find("Dot(e:GetForward())<0",1,true)and v4:find("garbageCapacity",1,true),"server requires rear of allowed truck and capacity")
ok(core:find("контейнер не",1,true)==nil and core:find("j.garbageDelivered",1,true),"dump unloads physical truck cargo")
ok(core:find("taxiStandby=true",1,true)and core:find("ожидайте живые заказы",1,true),"taxi job is a live standby shift")
ok(v4:find("function JB.CallTaxi",1,true)and v4:find('s=="/calltaxi"',1,true),"players call taxi through chat")
ok(v4:find("TaxiRequests",1,true)and v4:find("acceptTaxi",1,true)and v4:find("GRM_Taxi_RequestSweep",1,true),"taxi dispatch lifecycle")
ok(v4:find("PlayerEnteredVehicle",1,true)and v4:find("Поездка на такси",1,true),"passenger boarding pays driver")
ok(v4:find("JB.PushTracker(driver)",1,true)and v4:find("Маркер клиента",1,true),"accepted call creates driver marker")
ok(mobile:find('apps[#apps + 1] = "Такси"',1,true)and mobile:find('op=="taxi_call"',1,true)and mobile:find('M.screen=="taxi"',1,true),"smartphone taxi app calls live dispatch")
ok(dealer:find("VD.VehicleKinds",1,true)and dealer:find("job_taxi",1,true)and dealer:find("job_garbage",1,true)and dealer:find("job_courier",1,true),"dealer distinguishes personal/government/public/job vehicles")
ok(dealer:find("GRM_VehicleKind",1,true)and dealer:find("GRM_WorkVehicle",1,true),"spawned vehicle carries authoritative classification")
ok(dealerUI:find("Государственный",1,true)and dealerUI:find("Общественный",1,true)and dealerUI:find("Работа: такси",1,true),"dealer admin UI selects classification")
print(("JOBS V4: %d checks, failures=%d"):format(n,fail));os.exit(fail==0 and 0 or 1)
