-- Contracts for GRM Electronics/Internet ecosystem and destructible money printer.
local function read(p)local f=assert(io.open(p,"rb"));local s=f:read("*a");f:close();return s end
local core,client,photo,tool=read("lua/autorun/sh_grm_electronics.lua"),read("lua/autorun/client/cl_grm_electronics.lua"),read("lua/autorun/client/cl_grm_photorobot.lua"),read("lua/weapons/gmod_tool/stools/grm_network_tool.lua")
local printer,printerShared,deviceBase=read("lua/entities/grm_money_printer/init.lua"),read("lua/entities/grm_money_printer/shared.lua"),read("lua/entities/grm_net_device/init.lua")
local hub,qmenu=read("lua/autorun/server/sv_grm_persistence_hub.lua"),read("lua/autorun/sh_grm_qmenu.lua")
local pass,fail=0,0;local function has(s,n)return s:find(n,1,true)~=nil end;local function ok(v,n)if v then pass=pass+1;print("  ok  "..n)else fail=fail+1;print("  FAIL "..n)end end
ok(has(core,'E.Version="2.1.0"'),"electronics ecosystem version 2.1.0 (автосейв + фотомодуль)")
ok(has(core,"function E.RegisterDevice")and has(core,"function E.NetworkRouter")and has(core,"function E.IsOnline"),"authoritative device registry and online resolver")
ok(has(core,"connectedRouter")and has(core,"wifiAuthorized")and has(core,"passwordHash"),"Wi-Fi SSID/password authorization")
ok(has(core,'(op=="register"or op=="login")and not E.IsOnline(ent)'),"login and registration are rejected on offline computers")
ok(has(core,"function E.Link")and has(core,"function E.UnlinkDevice")and has(core,"E.Links"),"persistent physical cable graph")
ok(has(core,'util.SHA256')and has(core,"salt")and has(core,"passwordHash=hash(password,salt)"),"account passwords stored as salted hashes")
ok(has(core,"E.Accounts")and has(core,"E.Files")and has(core,"file_save")and has(core,"file_share")and has(core,"file_delete"),"accounts database and file transfer operations")
ok(has(core,"function E.EnsureAdminTelecom")and has(core,'hash("AdminTelecom",salt)')and has(core,'role="root"'),"built-in AdminTelecom account has a hashed root role")
ok(has(core,"function E.IsNetworkAdmin")and has(core,'s.role=="root"'),"authenticated AdminTelecom receives network admin authority")
ok(has(core,"65536")and has(core,"sharedWith"),"file size cap and per-user sharing")
ok(has(core,'op=="print"')and has(core,'grm_net_document'),"network printer produces physical documents")
ok(has(core,"allowFaction")and has(core,"allowArrest")and has(core,"allowFines")and has(core,"allowCCTV")and has(core,"allowRoomTap"),"faction arrest fine CCTV and wiretap integration gates")
ok(has(core,"GRM.Arrest.FactionOf")and has(core,"GRM.Wanted.GetLevel")and has(core,"GRM.CCTV")and has(core,"GRM.RoomTap"),"GRM module data integrations")
ok(has(core,"function E.SaveMap")and has(core,"function E.SaveDB")and has(core,'version=2,accounts=accounts,files=allFiles,mailbox=mailbox'),"map and database persistence")
ok(has(core,'util.JSONToTable,file.Read(path,"DATA")or"",false,true'),"safe 64-bit JSON parsing")
ok(has(core,'file.Read(path,"DATA")~=raw')and has(core,'path..".backup"'),"read-back and backup persistence")
ok(has(client,"GRM NET OS")and has(client,"appTile")and has(client,"Сетевые модули")and has(client,"Администрирование"),"modern clickable GRM desktop with icon applications")
ok(has(client,"formatModule")and not has(client,"SetText(util.TableToJSON(payload.module"),"module applications render readable UI instead of raw JSON")
ok(has(client,"secureEntry")and has(client,"GRMSecret")and not has(client,"SetPassword(true)"),"password fields use a custom masked GRM entry without invalid DTextEntry calls")
ok(has(client,"НАСТРОЙКА СЕТЕВОГО УСТРОЙСТВА")and has(client,"Фракционная база")and has(client,"Прослушка"),"visual access checkbox settings")
ok(has(client,"GRM NETWORK CONTROL CENTER")and has(client,"Удалить кабели")and has(client,"Удалить устройство"),"modern superadmin topology control center")
ok(has(client,'current.data.role=="root"')and has(client,'send(ent,"control_center")'),"AdminTelecom desktop exposes full Network Control Center")
ok(has(core,"function E.AdminPayload")and has(core,'"/grm_network_admin"')and has(core,'GRM_Net_AdminAction'),"admin control center uses direct authoritative actions")
ok(has(client,"GRM_Net_Cables")and has(client,"render.DrawBeam")and has(core,"constraint.Rope"),"physical rope cables and clear world rendering")
ok(has(tool,"Установка устройства")and has(tool,"Соединение кабелем")and has(tool,"Shift+R"),"single understandable network tool")
ok(has(tool,'undo.Create("GRM Network Device")')and has(tool,'undo.Create("GRM Network Cable")')and has(tool,"cleanup.Add"),"spawned devices and cables support Z undo and cleanup")
ok(has(core,"function E.HandleDeviceRemoved")and has(core,"function E.RemoveLink")and has(core,"GRM_Net_CleanupGuard")and has(deviceBase,"HandleDeviceRemoved"),"undo/remover deletion updates map database without breaking map cleanup")
ok(has(tool,"models/natalya/sims/computer.mdl")and has(tool,"models/props/cs_office/computer.mdl")and has(tool,"models/cheeze/wires/router.mdl"),"requested computer and router models exposed")
ok(has(tool,"models/props_lab/incubatorplug.mdl")and has(tool,"models/props_lab/tpplugholder_single.mdl"),"requested plug and wall socket models exposed")
ok(has(qmenu,'id = "grm_network_tool"')and has(hub,"electronics ="),"Q-menu and persistence hub integrations")
ok(has(printer,"function ENT:SetPrinterOwner")and has(printer,"function ENT:PrintMoney")and has(printer,"function ENT:IsOwner"),"money printer owner/printing contract")
ok(has(printer,"function ENT:OnTakeDamage")and has(printer,"TakePhysicsDamage")and has(printer,"DestroyPrinter"),"money printer takes real physical damage")
ok(has(printer,"GRM_MoneyPrinter_PhysgunPickup")and has(printer,"return true"),"owner/superadmin physgun movement remains enabled")
ok(has(printerShared,"Money Printer v2.1.0")and has(printer,"maxHealth = 250"),"printer v2.1 health contract")
-- Miniature topology behavior: link chain reaches router, unrelated endpoint does not.
local links={{a="pc",b="socket"},{a="socket",b="router"}};local kinds={pc="computer",socket="socket",router="router",other="computer"};local function route(start)local seen={[start]=true};local q={start};while#q>0 do local cur=table.remove(q,1);if kinds[cur]=="router"then return cur end;for _,l in ipairs(links)do local o=l.a==cur and l.b or(l.b==cur and l.a);if o and not seen[o]then seen[o]=true;q[#q+1]=o end end end end
ok(route("pc")=="router"and route("other")==nil,"cable graph resolves only connected network")
-- v1.4 features: per-device files, new apps, mail, printer model
ok(has(core,"E.Files[devID]")and has(core,"filesFor(ply,devID)"),"files stored per-device not globally")
ok(has(core,'op=="inbox"')and has(core,'op=="mail_send"')and has(core,"E.Mailbox"),"mailbox and distribution system")
ok(has(core,"GRM_Net_MailSend")and has(core,"[РАССЫЛКА]"),"admin broadcast mail to all users")
ok(has(client,"КАЛЬКУЛЯТОР")and has(client,"calcPage"),"calculator application")
ok(has(client,"ЗАМЕТКИ")and has(client,"notesPage"),"notes application")
ok(has(client,"ТЕКСТОВЫЙ РЕДАКТОР")and has(client,"editorPage"),"text editor application")
ok(has(client,"ФОТОРОБОТ")and has(client,"photoPage")and has(client,"GRM.Photorobot")and has(client,"photoCtx"),"photo robot app delegated to GRM.Photorobot module via context")
ok(has(client,"ПОЧТА / РАССЫЛКА")and has(client,"mailPage"),"mail and distribution application")
ok(has(client,"РАССЫЛКА ВСЕМ")and has(photo,"РАССЫЛКА ФОТОРОБОТА"),"broadcast and photo distribution")
ok(has(core,'op=="print"')and has(core,"paperSize")and has(core,"copies"),"printer job with paper size orientation copies quality")
ok(has(tool,"models/props_interiors/printer.mdl"),"updated printer model")
ok(has(core,"E.Files[id]=nil")and has(core,"E.Files[devID][r.id]"),"file cleanup on device removal and per-device store")
ok(has(photo,"PR.SkinTones")and has(photo,"PR.HairColors")and has(photo,"PR.EyeColors"),"photorobot module: skin hair eye palettes")
ok(has(photo,"sepia")and has(photo,"vintage")and has(photo,"grain"),"photorobot module: photo effects sepia vintage grain")
ok(has(photo,"render.Capture")and has(photo,"GetRenderTarget")and has(photo,"GRMFACE"),"photorobot module: RT capture + own GRMFACE format")
ok(has(photo,"Подозр. 1")and has(photo,"presets"),"photorobot module: preset suspect templates")
ok(has(photo,"PR.Parts")and has(photo,"face = {")and has(photo,"eyes = {")and has(photo,"nose = {"),"photorobot module: layered face eyes nose parts")
print(("ELECTRONICS: %d/%d failures=%d"):format(pass,pass+fail,fail));if fail>0 then os.exit(1)end
