-- Runtime smoke for real sh_grm_electronics.lua.
local pass,fail=0,0;local function ok(v,n)if v then pass=pass+1;print("  ok  "..n)else fail=fail+1;print("  FAIL "..n)end end
SERVER,CLIENT=true,false
function AddCSLuaFile()end;function isstring(v)return type(v)=="string"end;function istable(v)return type(v)=="table"end;function IsValid(v)return type(v)=="table"and v.valid~=false end;function string.Trim(s)return tostring(s):match("^%s*(.-)%s*$")end;math.Clamp=function(v,a,b)return math.max(a,math.min(b,v))end;table.Copy=function(t)local o={};for k,v in pairs(t or{})do o[k]=type(v)=="table"and table.Copy(v)or v end;return o end
local V={};V.__index=V;function Vector(x,y,z)return setmetatable({x=x or 0,y=y or 0,z=z or 0},V)end;function V:DistToSqr(o)local x,y,z=self.x-o.x,self.y-o.y,self.z-o.z;return x*x+y*y+z*z end;function Angle(p,y,r)return{p=p or 0,y=y or 0,r=r or 0}end
local TT=100;function CurTime()return TT end;function SysTime()return TT end;game={GetMap=function()return"gm_test"end};local files,json={},{ };file={IsDir=function()return true end,CreateDir=function()end,Exists=function(p)return files[p]~=nil end,Read=function(p)return files[p]end,Write=function(p,s)files[p]=s end};util={AddNetworkString=function()end,CRC=function(s)return tostring(#s).."x"end,SHA256=function(s)return"H"..s end,TableToJSON=function(t)local k="J"..(#json+1);json[k]=table.Copy(t);return k end,JSONToTable=function(s)return table.Copy(json[s])end,IsValidModel=function()return true end}
local recv={};net={Receive=function(n,f)recv[n]=f end,Start=function()end,WriteBool=function()end,WriteString=function()end,WriteTable=function()end,Send=function()end,Broadcast=function()end};hook={Add=function()end,Run=function()end};timer={Create=function()end,Simple=function()end};concommand={Add=function()end};scripted_ents={GetStored=function()return true end};player={GetAll=function()return{}end};ents={FindByClass=function()return{}end,Create=function()return{valid=false}end}
GRM={Identity={CharacterKey=function()return"765:char1"end}}
local chunk,err=loadfile("lua/autorun/sh_grm_electronics.lua");ok(chunk~=nil,"real electronics core parses: "..tostring(err));if not chunk then os.exit(1)end;local ran,rerr=pcall(chunk);ok(ran,"real electronics core executes: "..tostring(rerr));local E=GRM.Electronics
E.LoadDB();local root=E.Accounts.admintelecom;ok(root and root.role=="root"and root.passwordHash==util.SHA256("AdminTelecom:"..root.salt),"AdminTelecom bootstrap account is reproducible and hashed")
local adminPly={valid=true};function adminPly:IsSuperAdmin()return false end;E.Sessions[adminPly]={username="admintelecom",role="root",expires=CurTime()+60};ok(E.IsNetworkAdmin(adminPly)==true,"root network session grants admin control without Garry's Mod superadmin")
local function dev(id,kind,x,network)local d={valid=true,id=id,kind=kind,pos=Vector(x,0,0),network=network or"GRM-NET",active=true,name=id,owner=""};function d:EntIndex()return #self.id*100+(string.byte(self.id,#self.id)or 1)end;function d:GetDeviceID()return self.id end;function d:SetDeviceID(v)self.id=v end;function d:GetDeviceKind()return self.kind end;function d:GetDeviceActive()return self.active end;function d:GetPos()return self.pos end;function d:GetNetworkID()return self.network end;function d:GetDisplayName()return self.name end;function d:GetOwnerKey()return self.owner end;function d:GetOwnerName()return""end;function d:GetClass()return"grm_net_"..self.kind end;function d:GetModel()return"model"end;function d:GetAngles()return Angle()end;return d end
local router,plug,pc=dev("router","router",0),dev("plug","plug",100),dev("pc","computer",200)
E.RegisterDevice(router);E.RegisterDevice(plug);E.RegisterDevice(pc);E.Configs.router.range=500;E.Configs.router.passwordHash="locked";E.Links.a={id="a",a="pc",b="plug"};E.Links.b={id="b",a="plug",b="router"}
ok(E.NetworkRouter(pc)==router,"wired computer resolves router through plug graph")
E.Links={};ok(E.NetworkRouter(pc)==nil,"password-protected Wi-Fi does not auto-connect")
E.Configs.pc.connectedRouter="router";E.Configs.pc.wifiAuthorized=true;ok(E.NetworkRouter(pc)==router,"authorized Wi-Fi connection resolves router")
ok(E.SaveMap()==true and files[E.MapFile]~=nil,"map topology saves with read-back")
print(("ELECTRONICS RUNTIME: %d/%d failures=%d"):format(pass,pass+fail,fail));if fail>0 then os.exit(1)end
