-- Contracts for GRM Vehicle Dealer & Garage v3.
local function read(p)local f=assert(io.open(p,"rb"));local s=f:read("*a");f:close();return s end
local core,ent,cl,tool,q,doors,perm = read("lua/autorun/sh_grm_vehicle_dealer.lua"),read("lua/entities/sent_vehicle_dealer/init.lua"),read("lua/entities/sent_vehicle_dealer/cl_init.lua"),read("lua/weapons/gmod_tool/stools/grm_transport.lua"),read("lua/autorun/sh_grm_qmenu.lua"),read("lua/autorun/sh_grm_doors.lua"),read("lua/autorun/sh_grm_perm_entities.lua")
local checks,failed=0,0;local function has(s,n)return s:find(n,1,true)~=nil end;local function ok(v,n)checks=checks+1;if v then print("  ok "..checks..". "..n)else failed=failed+1;print("  FAIL "..checks..". "..n)end end
ok(has(core,'VD.Version="3.8.0"'),"dealer v3.8: гаражи, лимит по классу, режимы выдачи, выкуп государством")
ok(has(core,"VD.GarageFile")and has(core,"CharacterKey"),"garage persists per CharacterKey")
ok(has(core,"function VD.VehicleInfo")and has(core,'list.Get("simfphys_vehicles")')and has(core,'list.Get("LVS_Vehicles")'),"Source simfphys and LVS registries")
ok(has(core,"SpawnVehicleSimple")and has(core,"simfphys fallback")and has(core,"LVS SpawnFunction")and has(core,"scripted entity"),"legacy-compatible multi-stage vehicle spawn fallbacks")
ok(has(core,"function VD.FindDeliveryPosition")and has(core,"function VD.FindSpawnPoint")and has(core,"TraceHull")and has(core,"Площадка выдачи занята"),"delivery point/zone searches safe unoccupied points")
ok(has(core,"hasSpawnZone")and has(core,"spawnZoneMin")and has(core,"spawnZoneMax")and has(core,"SetSpawnPos(hasPad and((padMin+padMax)*.5)or legacyPoint)"),"zone persisted; legacy point stays a point (v3.1.2)")
ok(has(tool,"GRM_Transport_ToolReq")and has(tool,"DrawWireframeBox")and has(tool,"spawnPos"),"transport tool requests and draws garages, slots and dealer points")
ok(has(cl,"self:GetDealerName()")and has(cl,"OBBMaxs().z")and has(cl,"ТРАНСПОРТНЫЙ ЦЕНТР"),"configured dealer name is rendered above NPC")
ok(has(core,'op=="buy"')and has(core,'op=="retrieve"')and has(core,'op=="store"')and has(core,'op=="sell"'),"buy retrieve store and sell operations")
ok(has(core,"saveGarage()")and has(core,"PlayerDisconnected"),"garage saves and stores vehicles on disconnect")
ok(has(core,"function _G.VD_RemoveDealerVehicle"),"context-menu compatibility stores vehicles in garage")
ok(has(core,"GRM_VD_GarageCommand")and has(core,'"/garage"'),"garage chat command opens nearest dealer")
ok(has(core,"function VD.SaveDealer")and has(core,"function VD.LoadDealers")and has(core,"migrateLegacyDealers"),"dealer persistence and legacy migration")
ok(has(ent,"GRM.VehicleDealer.Push")and #ent<2500,"dealer entity is thin and authoritative")
ok(has(cl,"GRM / ТРАНСПОРТНЫЙ ЦЕНТР")and has(cl,"Гараж")and has(cl,"GRM_VD_Result"),"GRM-styled dealer and garage UI")
ok(has(cl,"GRM_VD_AdminOpen")and has(cl,"СОХРАНИТЬ ДИЛЕРА, АССОРТИМЕНТ И ГАРАЖ"),"GRM admin assortment UI")
ok(has(tool,"GRM: транспорт")and has(tool,"SaveDealer"),"unified transport tool auto-saves dealers")
ok(has(q,'id = "grm_transport"')and not has(q,'id = "vehicle_dealer_tool"')and not has(q,'id = "grm_garage",')and has(q,'id = "grm_door_admin"'),"Q-menu exposes ONE transport tool, old ones removed")
ok(not has(perm,"sent_vehicle_dealer = true"),"generic perm cannot duplicate dedicated dealers")
ok(has(doors,"GRM_Doors_SuppressDuplicateHUD"),"door HUD duplicate suppression is persistent")
ok(has(core,"vehicle_dealers")or has(read("lua/autorun/server/sv_grm_persistence_hub.lua"),"vehicle_dealers"),"unified persistence includes dealers")
ok(has(core,"function VD.SetSpawnPoint")and has(core,"function VD.ClearSpawnPoint"),"spawn point API (set/clear)")
ok(has(core,"Точка выдачи занята")and has(core,"dealer:GetSpawnAngle()"),"spawn point fallback and occupied message")
ok(has(tool,"grm_transport_direction")and has(tool,'key = "dealerpoint"')and has(tool,"SetSpawnPoint"),"direction selector and dealer point placement in tool")
ok(has(tool,"ТОЧКА ВЫДАЧИ ДИЛЕРА")and has(tool,"высота %d"),"point marker and lift label drawn")
ok(has(tool,"По взгляду при установке")and has(tool,"Влево от дилера")and has(tool,"Вправо от дилера"),"direction choices: look/left/right")
ok(has(core,"ent:SetPos(base+Vector(0,0,lift))")and has(core,"b2+Vector(0,0,lift)"),"lift re-applied after drop and after async simfphys settle")
-- Т-поза дилера после каждой правки настроек (заказ владельца 19.08).
local shared=read("lua/entities/sent_vehicle_dealer/shared.lua")
local entInit=read("lua/entities/sent_vehicle_dealer/init.lua")
local animFix=read("lua/autorun/server/sv_grm_vehicle_dealer_anim_fix.lua")
ok(has(shared,"function ENT:ApplyIdleAnimation"),"idle-анимация ставится одной общей функцией")
ok(has(shared,"function ENT:ApplyDealerModel"),"смена модели идёт через ApplyDealerModel (модель + idle)")
ok(has(shared,'current ~= "reference"'),"сторож узнаёт Т-позу по последовательности reference")
ok(has(entInit,"self:ApplyIdleAnimation(true)"),"дилер встаёт в idle при создании")
ok(has(entInit,"function ENT:Think")and has(entInit,"self._grmIdleCheck"),"сторож анимации с троттлингом раз в 2 сек")
ok(has(core,"if ent.ApplyDealerModel then ent:ApplyDealerModel(model)"),"загрузка карты не оставляет дилера в Т-позе")
ok(has(core,"if dealer.ApplyDealerModel then dealer:ApplyDealerModel(model)"),"сохранение настроек возвращает анимацию")
ok(has(core,"elseif dealer.ApplyIdleAnimation then dealer:ApplyIdleAnimation(true)end"),
    "даже при пустой/неверной модели анимация чинится")
ok(has(animFix,"if ent.ApplyIdleAnimation then ent:ApplyIdleAnimation(true) return end"),
    "старый патч анимации делегирует энтити, второй копии списка нет")

print(("VEHICLE DEALER V3: %d/%d failures=%d"):format(checks-failed,checks,failed));if failed>0 then os.exit(1)end
